version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
    - "5432:5432"
    volumes:
    - /Users/mateusnascimento/Documents/nodejs/graphql/setup-typegraphql/data/postgres:/Users/mateusnascimento/Documents/nodejs/graphql/setup-typegraphql/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=snackbars
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /Users/mateusnascimento/Documents/nodejs/graphql/setup-typegraphql/data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=admin
 
networks:
  postgres:
    driver: bridge